server:
  port: 8080

chroma:
  host: ${CHROMA_HOST:localhost}
  port: ${CHROMA_PORT:8000}
  collection-name: ${CHROMA_COLLECTION:spring-ai-docs}

openai:
  api-key: ${OPENAI_API_KEY:demo}
  model: text-embedding-ada-002

logging:
  level:
    com.example.springaichroma: DEBUG
    root: INFO